#! /usr/bin/env sh

# -- check commands are present
for cmd in fzf pcregrep; do
  if ! hash "$cmd" 2> /dev/null
  then
    echo "$cmd could not be found on PATH"
    exit 1
  fi
done


VAULT=$(pcregrep -o1 'vault:\s*"(.+)"' ~/.config/diatom.yaml)


if [ "$OSTYPE" = 'linux' ]
then
  query_selection_pair="$(ls --quoting-style=literal "$VAULT" | fzf --tac --print-query --exact --preview="batcat --color always --language markdown $VAULT/{}")"
else
  query_selection_pair="$(ls "$VAULT" | fzf --tac --print-query --exact --preview="batcat --color always --language markdown $VAULT/{}")"
fi


query=$(echo "$query_selection_pair" | sed -n '1 p')
selection=$(echo "$query_selection_pair" | sed -n '2 p')


if [ -z "$query" ] && [ -z "$selection" ]
then
  echo 'no input or selection provided'
  exit 1
elif [ -z "$selection" ];
then
  # -- nothing selected, create a new file

  di new note "$query" "$@"
else
  # -- open selected file

  di open note "$selection" "$@"
fi
